# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"split_array": "00_core.ipynb",
         "r3": "00_core.ipynb",
         "agg_var": "00_core.ipynb",
         "agg_std": "00_core.ipynb",
         "agg_score": "00_core.ipynb",
         "Aggs": "00_core.ipynb",
         "mse": "00_core.ipynb",
         "rmse": "00_core.ipynb",
         "add_dateparts": "10_data.ipynb",
         "fix_missing": "10_data.ipynb",
         "numericalize": "10_data.ipynb",
         "proc_df": "10_data.ipynb",
         "DataWrapper": "10_data.ipynb",
         "Node": "20_models.ipynb",
         "best_split_for_col": "20_models.ipynb",
         "best_split": "20_models.ipynb",
         "DecisionTree": "20_models.ipynb",
         "print_tree": "20_models.ipynb",
         "predict_row": "20_models.ipynb",
         "TreeEnsemble": "20_models.ipynb",
         "export_from_data_to_core": "40_export_with_module.ipynb",
         "exports_from_data_to_core": "40_export_with_module.ipynb",
         "exporti_from_data_to_core": "40_export_with_module.ipynb",
         "fn_in_export_with_module": "40_export_with_module.ipynb"}

modules = ["core.py",
           "data.py",
           "models.py",
           "export_with_module.py"]

doc_url = "https://pete88b.github.io/decision_tree/"

git_url = "https://github.com/pete88b/decision_tree/tree/master/"

def custom_doc_links(name): return None
