# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"split_array": "00_core.ipynb",
         "export_from_data_to_core": "10_data.ipynb",
         "add_dateparts": "10_data.ipynb"}

modules = ["core.py",
           "data.py"]

doc_url = "https://pete88b.github.io/decision_tree/"

git_url = "https://github.com/pete88b/decision_tree/tree/master/"

def custom_doc_links(name): return None
