# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"A": "51_test_show_doc.ipynb",
         "B": "51_test_show_doc.ipynb",
         "split_array": "00_core.ipynb",
         "r3": "00_core.ipynb",
         "agg_var": "00_core.ipynb",
         "agg_std": "00_core.ipynb",
         "agg_score": "00_core.ipynb",
         "Aggs": "00_core.ipynb",
         "mse": "00_core.ipynb",
         "rmse": "00_core.ipynb",
         "add_dateparts": "10_data.ipynb",
         "fix_missing": "10_data.ipynb",
         "numericalize": "10_data.ipynb",
         "proc_df": "10_data.ipynb",
         "DataWrapper": "10_data.ipynb",
         "TestClassThatDoesNothing": "10_data.ipynb",
         "Node": "20_models.ipynb",
         "best_split_for_col": "20_models.ipynb",
         "best_split": "20_models.ipynb",
         "DecisionTree": "20_models.ipynb",
         "print_tree": "20_models.ipynb",
         "predict_row": "20_models.ipynb",
         "TreeEnsemble": "20_models.ipynb",
         "export_from_data_to_core": "40_test_export.ipynb",
         "exports_from_data_to_core": "40_test_export.ipynb",
         "exporti_from_data_to_core": "40_test_export.ipynb",
         "export_no_module": "40_test_export.ipynb",
         "exporti_no_module": "40_test_export.ipynb",
         "exports_no_module": "40_test_export.ipynb",
         "AnotherTestClass": "50_test_doc.ipynb",
         "c": "51_test_show_doc.ipynb",
         "A.NestedA.e": "51_test_show_doc.ipynb",
         "d": "51_test_show_doc.ipynb",
         "Tensor.tsne": "71_tensor_patch.ipynb",
         "in_ipython": "73_in_ipython.ipynb",
         "in_ipython2": "73_in_ipython.ipynb"}

modules = ["exports_to_target_module.py",
           "target_module.py",
           "core.py",
           "data.py",
           "models.py",
           "test/export.py",
           "test/doc.py",
           "test/show_doc.py",
           "test/all.py",
           "test/add2__all__.py",
           "test/tensor_patch.py",
           "test/expif.py",
           "test/in_ipython.py"]

doc_url = "https://pete88b.github.io/decision_tree/"

git_url = "https://github.com/pete88b/decision_tree/tree/master/"

def custom_doc_links(name): return None
