# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['split_array', 'export_from_data_to_core']

# Cell
def split_array(data, idx): return data[:idx], data[idx:]

# Comes from 10_data.ipynb, cell
def export_from_data_to_core():
    "export to a different module"
    pass