# AUTOGENERATED! DO NOT EDIT! File to edit: 10_data.ipynb (unless otherwise specified).

__all__ = ['add_dateparts']

# Cell
# from decision_tree.imports import *
from .core import *

# Cell
def add_dateparts(df, col):
    """converts a column of df from a datetime64 to many columns containing
    the information from the date - inplace."""
    targ_pre = re.sub('[Dd]ate$', '', col.name)
    attrs = ['Year', 'Month', 'Week', 'Day', 'Dayofweek', 'Dayofyear',
             'Is_month_end', 'Is_month_start', 'Is_quarter_end', 'Is_quarter_start',
             'Is_year_end', 'Is_year_start']
    for attr in attrs: df[targ_pre + attr] = getattr(col.dt, attr.lower())
    df[targ_pre + 'Elapsed'] = col.astype(np.int64) // 10**9
    df.drop(col.name, axis=1, inplace=True)