# AUTOGENERATED! DO NOT EDIT! File to edit: 001_exports_to_target_module.ipynb (unless otherwise specified).

__all__ = ['A']

# Cell
class A:
    """The Class A."""
    def __init__(self, value):
        self.value = value