# AUTOGENERATED! DO NOT EDIT! File to edit: 40_export_with_module.ipynb (unless otherwise specified).

__all__ = ['fn_in_export_with_module']

# Cell
from .core import *

# Cell
def fn_in_export_with_module():
    """Doesn't really do anything."""
    pass