# AUTOGENERATED! DO NOT EDIT! File to edit: 40_test_export.ipynb (unless otherwise specified).

__all__ = ['export_no_module', 'exports_no_module']

# Cell
from .core import *

# Cell
def export_no_module():
    """Doesn't really do anything."""
    pass

# Internal Cell
def exporti_no_module():
    """Doesn't really do anything."""
    pass

# Cell
def exports_no_module():
    """Doesn't really do anything."""
    pass