# AUTOGENERATED! DO NOT EDIT! File to edit: 002_target_module.ipynb (unless otherwise specified).

__all__ = ['B']

# Comes from 001_exports_to_target_module.ipynb, cell
class B:
    """The Class B."""
    def __init__(self, value):
        self.value = value