# AUTOGENERATED! DO NOT EDIT! File to edit: 61_test_add2__all__.ipynb (unless otherwise specified).

__all__ = ['_not_included_by_default', '_not_included_by_default2', 'a']

# Cell
def _not_included_by_default(): pass

# Cell
def _not_included_by_default2(): pass

# Cell


# Cell


# Cell


# Cell
if True:
    a=2

# more comments ...
if False: a=3