# AUTOGENERATED! DO NOT EDIT! File to edit: 61_test_add2__all__.ipynb (unless otherwise specified).

__all__ = ['_not_included_by_default', '_not_included_by_default2', '_not_included_by_default2',
           '_not_included_by_default2', 'a']

# Cell
def _not_included_by_default(): pass
#nbdev_comment _all_=[_not_included_by_default]

# Cell
def _not_included_by_default2(): pass
#nbdev_comment %nbdev_add2all ["_not_included_by_default2"]

# Cell


# Cell


# Cell


# Cell
if True:
    a=2
#nbdev_comment %nbdev_add2all a
# more comments ...
if False: a=3