# AUTOGENERATED! DO NOT EDIT! File to edit: 50_test_doc.ipynb (unless otherwise specified).

__all__ = ['AnotherTestClass']

# Internal Cell
class _TstClass():
    "It's a test class"
    def a(self):
        "no flag"
        pass
    def b(self):
        "hide flag"
        pass
    def c(self):
        "hide_input flag"
        pass
    def d(self):
        "hide_output flag"
        pass

# Cell
class AnotherTestClass():
    "just another test class"
    def a():
        "with a dummy method"
        pass

# Cell
print('exported and shown')