# AUTOGENERATED! DO NOT EDIT! File to edit: 72_if__name__.ipynb (unless otherwise specified).

__all__ = []

# Cell
if __name__ == "__main__":
    print("Run when invoked directly.")
else:
    print("Run when imported.")

# Cell
try: from nbdev.imports import IN_NOTEBOOK
except: IN_NOTEBOOK=False
print("Running in notebook" if IN_NOTEBOOK else "Not running in notebook")

# Cell
if __name__ == "__main__" and not IN_NOTEBOOK:
    print('Running "command line" logic ...')