# AUTOGENERATED! DO NOT EDIT! File to edit: 74_from_future_import.ipynb (unless otherwise specified).


from __future__ import annotations



from __future__ import unicode_literals
from __future__ import generator_stop


__all__ = ['Tree', 'annotations']

# Cell
# borrowed from https://realpython.com/python37-new-features/
class Tree:
    def __init__(self, left: Tree, right: Tree) -> None:
        self.left = left
        self.right = right

# Cell
#nbdev_comment from __future__ import unicode_literals
#nbdev_comment from __future__ import generator_stop

# Cell
# this is just here to demo nb->lib and lib->nb when using add2all