# AUTOGENERATED! DO NOT EDIT! File to edit: 51_test_show_doc.ipynb (unless otherwise specified).

__all__ = ['A', 'B', 'c', 'd']

# Cell
from fastai2.imports import *
class A:
    "a class"
    class NestedA:
        "a nested class"
class B():
    "b class"
def c():
    "c func"
d="d is an object def"
@patch
def e(x:A.NestedA):
    "patch e onto A.NestedA"