# AUTOGENERATED! DO NOT EDIT! File to edit: 71_tensor_patch.ipynb (unless otherwise specified).

__all__ = ['Tensor']

# Cell
from fastai2.torch_basics import *
from nbdev.showdoc import *

# Cell
@patch
def tsne(x:Tensor, k=2, seed=47):
    "TSNE embeddings using `sklearn`"